### ISSUE TITLE
Add Python support

### ISSUE THREAD

**Issue by tombruijn** [appsignal/mono#50]
Split from https://github.com/appsignal/appsignal-python/issues/3

## To do

Keep in mind that the way we use Hatch is a bit unusual, so this might be less "implement Python/Hatch support for Mono" and more "implement custom scripts support for Mono"?

- [x] Check if we need to add full Python support right away, or if we can get away with using custom commands using `command` config.
  - Going for the custom commands route.
- [ ] ~Support Python so that we can ship releases for our Python package using mono - https://github.com/appsignal/appsignal-python~
- [ ] ~Add Python/Hatch support to Mono~
- [x] Remember to add this repo to [the backlog helper's changeset projects list](https://github.com/appsignal/backlog-helper/blob/835f62fd188fa4cfd842bc374008875d4913f108/lib/rules/user_config.rb#L38)!

**Comment by unflxw** [comment]
Ah, I did not know custom commands were already a thing that Mono supported! The way we build the package is not standard to Python (no such thing, really) or to Hatch (we use custom build scripts to trick Hatch into building for different platforms) so that probably would be the best way to go.

**Comment by tombruijn** [comment]
Looks like it needs a bit of work update the package version for other languages. PR #52 is a work in progress.

**Comment by tombruijn** [comment]
PR #52 merged. Mono config added to Python package: https://github.com/appsignal/appsignal-python/blob/0eb6fb93f048255f4452e01eda7a66975da95c34/mono.yml

Not yet tested with a full release, but let's iron out the issues as we run into it. Closing.
